linters:
  enable-all: true
  disable:
  - interfacer
  - maligned
  - scopelint
  - golint
  - gomnd
  - mnd
  - fieldalignment
  - gochecknoinits
  - depguard
  - gci
  - exhaustivestruct
  - exhaustruct
  - gochecknoglobals
  - gofumpt
  - forbidigo
  - varnamelen

issues:
  exclude-rules:
  # Exclude some linters from running on tests files.
  - path: _test\.go
    linters:
    - gocyclo
    - errcheck
    - dupl
    - gosec
    - goerr113
  fix: true
